In [107]:
import numpy as np
import torch



In [192]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37],
                   [69, 96, 70], 
                   
                  ], dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56],
                    [81],
                    [119], 
                    [22], 
                    [103],
                   
                    ],dtype='float32')



print(inputs)
print(targets)

[[ 73.  67.  43.]
 [ 91.  88.  64.]
 [ 87. 134.  58.]
 [102.  43.  37.]
 [ 69.  96.  70.]]
[[ 56.]
 [ 81.]
 [119.]
 [ 22.]
 [103.]]


In [193]:
#Convert inputs and targets to tensors

inputs=torch.from_numpy(inputs)
print(inputs)
targets=torch.from_numpy(targets)
print(targets)


tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [194]:
#Weight and biases

w= torch.randn(1,3,requires_grad=True)
print(w)
b=torch.randn(1,requires_grad=True)
print(b)



tensor([[0.5272, 0.9686, 1.3077]], requires_grad=True)
tensor([0.2827], requires_grad=True)


In [195]:
#Define The Model
def model(x):
  return torch.mm(x,w.t(),out=None)+b

In [196]:
#Generate Predictions
#Compare with Targets

preds=model(inputs)
print("Prediction: ",preds)
print("Targets: ",targets)



Prediction:  tensor([[159.8937],
        [217.1854],
        [251.7855],
        [144.0891],
        [221.1828]], grad_fn=<AddBackward0>)
Targets:  tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [197]:
#MSE loss
#Compute Loss

def mse(P,T):
  diff=0
  i=0
  sum=0
  n=len(T)
  for k in range(0,n):
    i+=1
    diff=T[k]-P[k]
    square=diff*diff
    sum+=square
  mean=sum/i
  return mean

output=mse(preds,targets)
print("Loss: ",output)

Loss:  tensor([15169.0518], grad_fn=<DivBackward0>)


In [198]:
#Compute Gradients
print("Gradient :",output.backward())

Gradient : None


In [199]:
#Gradient for weights
print(w)
print(w.grad)


tensor([[0.5272, 0.9686, 1.3077]], requires_grad=True)
tensor([[20854.8574, 21333.5312, 13469.9775]])


In [200]:
#Gradient for bias
print(b)
print(b.grad)

tensor([0.2827], requires_grad=True)
tensor([245.2546])


In [207]:
# Compute gradients
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()
print(w)
print(b)

tensor([[-0.3408,  0.6500,  0.9137]], requires_grad=True)
tensor([0.2734], requires_grad=True)


In [212]:
# Generate predictions
# Calculate the loss
new_preds=model(inputs)
new_loss=mse(new_preds,targets)
print("New Loss: ",new_loss)



New Loss:  tensor([23.3707], grad_fn=<DivBackward0>)


In [215]:
#Train for 100 Epochs
for i in range(100):
  preds=model(inputs)
  loss=mse(preds,targets)
  loss.backward()
  with torch.no_grad():
     w-=w.grad*1e-5
     b-=b.grad*1e-5
     w.grad.zero_()
     b.grad.zero_()

# print(preds)
# print(loss)

tensor([[ 57.1151],
        [ 83.2325],
        [116.4417],
        [ 20.6336],
        [104.0196]], grad_fn=<AddBackward0>)
tensor([3.1359], grad_fn=<DivBackward0>)


In [216]:
#Calculate the loss
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor([3.1277], grad_fn=<DivBackward0>)


Pytorch Built ins


In [96]:
# Imports
import torch.nn as nn

In [98]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37],[69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69,96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96,
70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]]
,dtype='float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)



In [99]:
from torch.utils.data import TensorDataset, DataLoader
